Close GUI before daemon is killed when upgrading app version
Closing the GUI shows the disconnected and unsecure notification and the
tray icon switches to the unlocked state when it loses the connection to
the daemon.

diff --git a/dist-assets/pkg-scripts/preinstall b/dist-assets/pkg-scripts/preinstall
--- a/dist-assets/pkg-scripts/preinstall
+++ b/dist-assets/pkg-scripts/preinstall
@@ -33,3 +33,15 @@ rm "$NEW_CACHE_DIR/api-ip-address.txt" || true
 
 # Remove deprecated exclusion group. This line can be removed when 2023.4 is no longer supported
 dscl . -delete /groups/mullvad-exclusion &>/dev/null || true
+
+# Kill the GUI before proceeding with the daemon upgrade.
+# TODO: Remove this when versions prior to 2022.5 is no longer supported.
+# Default behaviour should be to kill the GUI before the daemon, which can be
+# done from preinstall rather than postinstall.
+"$INSTALL_DIR"/Mullvad VPN.app/Contents/Resources/mullvad-setup is-older-version 2022.5
+KILL_GUI_BEFORE_DAEMON=$?
+if [[ $KILL_GUI_BEFORE_DAEMON -eq 0 ]]
+then
+  pkill -x "Mullvad VPN" || echo "Unable to kill GUI, not running?"
+  sleep 1
+fi
