Stop checking if the GUI should be killed before app install on macOS
Clean up the pre-install script on macOS. The GUI can and should be
unconditionally killed before running the install script since we have
dropped support for app version `2022.5`.

diff --git a/dist-assets/pkg-scripts/preinstall b/dist-assets/pkg-scripts/preinstall
--- a/dist-assets/pkg-scripts/preinstall
+++ b/dist-assets/pkg-scripts/preinstall
@@ -44,10 +44,4 @@ rm "$NEW_CACHE_DIR/api-ip-address.txt" || true
 dscl . -delete /groups/mullvad-exclusion &>/dev/null || true
 
 # Kill the GUI before proceeding with the upgrade.
-#
-# When we drop support for all app versions older than 2022.5, we can skip this
-# check and always try to kill the GUI.
-if "$INSTALL_DIR/Mullvad VPN.app/Contents/Resources/mullvad-setup" is-older-version 2022.5; then
-    pkill -x "Mullvad VPN" || echo "Unable to kill GUI, not running?"
-    sleep 1
-fi
+pkill -x "Mullvad VPN" && sleep 1 || echo "Unable to kill GUI, not running?"
