Migrate cache directory on macOS

diff --git a/dist-assets/pkg-scripts/preinstall b/dist-assets/pkg-scripts/preinstall
--- a/dist-assets/pkg-scripts/preinstall
+++ b/dist-assets/pkg-scripts/preinstall
@@ -57,33 +57,27 @@ if [ -d "$OLD_LOG_DIR" ]; then
     rm -rf "$OLD_LOG_DIR"
 fi
 
-# Migrate cache files from <=2018.1 paths
-OLD_CACHE_DIR="$HOME/Library/Caches/mullvad-daemon"
-NEW_CACHE_DIR="/var/root/Library/Caches/mullvad-vpn"
-if [ -d "$OLD_CACHE_DIR" ]; then
-    echo "Found old cache dir at $OLD_CACHE_DIR, moving to $NEW_CACHE_DIR"
-    mkdir -p "$NEW_CACHE_DIR"
-    mv "$OLD_CACHE_DIR"/* "$NEW_CACHE_DIR/" || echo "Unable to migrate cache. No cache files?"
-    rm -rf "$OLD_CACHE_DIR"
-fi
+# Migrate cache files from <=2020.8-beta2 paths
+OLD_CACHE_DIRS=(
+    "$HOME/Library/Caches/mullvad-daemon"
+    "/var/root/Library/Caches/mullvad-daemon"
+    "/var/root/Library/Caches/mullvad-vpn"
+)
+NEW_CACHE_DIR="/Library/Caches/mullvad-vpn"
 
-# Migrate cache files from <=2018.2-betaX paths
-OLD_CACHE_DIR="/var/root/Library/Caches/mullvad-daemon"
-NEW_CACHE_DIR="/var/root/Library/Caches/mullvad-vpn"
-if [ -d "$OLD_CACHE_DIR" ]; then
-    echo "Found old cache dir at $OLD_CACHE_DIR, moving to $NEW_CACHE_DIR"
-    mkdir -p "$NEW_CACHE_DIR"
-    mv "$OLD_CACHE_DIR"/* "$NEW_CACHE_DIR/" || echo "Unable to migrate cache. No cache files?"
-    rm -rf "$OLD_CACHE_DIR"
-fi
+for old_dir in "${OLD_CACHE_DIRS[@]}"; do
+    if [ -d "$old_dir" ]; then
+        echo "Found old cache dir at $old_dir, moving to $NEW_CACHE_DIR"
+        mkdir -p "$NEW_CACHE_DIR"
+        mv "$old_dir"/* "$NEW_CACHE_DIR/" || echo "Unable to migrate cache. No cache files?"
+        rm -rf "$old_dir"
+    fi
+done
 
 # Remove the existing relay and API address cache lists.
 # There is a risk that they're incompatible with the format this version wants
 rm "$NEW_CACHE_DIR/relays.json" || true
-# Old API IP cache
 rm "$NEW_CACHE_DIR/api-ip-address.txt" || true
-# New API IP cache
-rm "/Library/Caches/mullvad-vpn/api-ip-address.txt" || true
 
 # Notify the running daemon that we are going to kill it and replace it with a newer version.
 # This will make the daemon save it's state to a file and then lock the firewall to prevent
