Simplify scripts

diff --git a/scripts/setup-rust b/scripts/setup-rust
--- a/scripts/setup-rust
+++ b/scripts/setup-rust
@@ -5,7 +5,7 @@
 
 set -eu
 
-SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
+SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
 cd "$SCRIPT_DIR/.."
 
 source scripts/utils/log
@@ -20,79 +20,73 @@ IOS_TARGETS="aarch64-apple-ios-sim aarch64-apple-ios x86_64-apple-ios"
 IOS_COMPONENTS="rust-analyzer"
 
 function main {
-  if [ $# -eq 0 ]; then
-    print_usage
-    exit 1
-  fi
+    if [[ $# -eq 0 ]]; then
+        print_usage
+        exit 1
+    fi
 
-  case "$1" in
+    case "$1" in
     "android")
-      setup "Android" "$ANDROID_TARGETS" "$ANDROID_COMPONENTS" "${2:-}"
-      ;;
+        setup "Android" "$ANDROID_TARGETS" "$ANDROID_COMPONENTS"
+        ;;
     "desktop")
-      setup "Desktop" "$DESKTOP_TARGETS" "$DESKTOP_COMPONENTS" "${2:-}"
-      ;;
+        setup "Desktop" "$DESKTOP_TARGETS" "$DESKTOP_COMPONENTS"
+        ;;
     "ios")
-      setup "Android" "$IOS_TARGETS" "$IOS_COMPONENTS" "${2:-}"
-      ;;
+        setup "Android" "$IOS_TARGETS" "$IOS_COMPONENTS"
+        ;;
     "install-hook")
-      install_hook "${2:-}"
-      ;;
+        install_hook
+        ;;
+    "--help")
+        print_usage
+        exit 0
+        ;;
     *)
-      print_usage
-      exit 1
-      ;;
-  esac
+        log_error "Invalid argument: \`$1\`"
+        print_usage
+        exit 1
+        ;;
+    esac
 }
 
 function print_usage {
-  log "Setup default Rust targets and components for different platforms"
-  log ""
-  log "Usage: setup-rust android|desktop|ios|install-hook [--print-targets] [--print-components]"
-  log "  android                    Run Android-specific setup"
-  log "  desktop                    Run Desktop-specific setup"
-  log "  ios                        Run iOS-specific setup"
-  log "  install-hook [platform]    Copies the setup-rust-post-checkout file to .git/hooks/post-checkout"
-  log "                             Optionally supply a platform (android|desktop|ios) for the hook to use that"
-  log "                             platform as an argument to setup-rust (e.g. 'scripts/setup-rust install-hook android')"
-  log ""
-  log "Options:"
-  log "--print-targets        Only print the targets that would be added"
-  log "--print-components     Only print the components that would be added"
+    log "Setup default Rust targets and components for different platforms"
+    log ""
+    log "Usage: setup-rust android|desktop|ios|install-hook"
+    log "  android                    Run Android-specific setup"
+    log "  desktop                    Run Desktop-specific setup"
+    log "  ios                        Run iOS-specific setup"
+    log "  install-hook               Copies the setup-rust-post-checkout file to .git/hooks/post-checkout"
 }
 
 function setup {
-  case "$4" in
-    "--print-targets")
-      echo "$2"
-      ;;
-    "--print-components")
-      echo "$3"
-      ;;
-    *)
-      log "Installing default Rust targets/components"
-      log "platform: $1"
-      log "targets: $2"
-      log "components: $3"
-      # shellcheck disable=SC2086
-      rustup target add $2
-      # shellcheck disable=SC2086
-      rustup component add $3
-      ;;
-  esac
+    local PLATFORM=$1
+    local TARGETS=$2
+    local COMPONENTS=$3
+
+    log "Installing default Rust targets/components"
+    log "platform: $PLATFORM"
+    log "targets: $TARGETS"
+    log "components: $COMPONENTS"
+    # shellcheck disable=SC2086
+    rustup target add $2
+    # shellcheck disable=SC2086
+    rustup component add $3
 }
 
 function install_hook {
-  local hook=$SCRIPT_DIR/../.git/hooks/post-checkout
-  if [ -f "$hook" ]; then
-    log_error "$(realpath "$hook") file already exists - will not overwrite"
-    exit 1
-  else
-    cp "$SCRIPT_DIR/setup-rust-post-checkout" "$hook"
-    chmod +x "$hook"
-  fi
+    local hook=$SCRIPT_DIR/../.git/hooks/post-checkout
+    if [[ -f "$hook" ]]; then
+        log_error "$(realpath "$hook") file already exists - will not overwrite"
+        exit 1
+    else
+        cp "$SCRIPT_DIR/setup-rust-post-checkout" "$hook"
+        chmod +x "$hook"
+        log "Hook installed. You must now set the environment variable MULLVAD_SETUP_PLATFORM to "
+        log "\`android\`, \`desktop\` or \`ios\` in your shell environment."
+    fi
 }
 
 # Run script
 main "$@"
-
diff --git a/scripts/setup-rust-post-checkout b/scripts/setup-rust-post-checkout
--- a/scripts/setup-rust-post-checkout
+++ b/scripts/setup-rust-post-checkout
@@ -1,72 +1,28 @@
 #!/usr/bin/env bash
 #
-# To install the hook copy this file to `.git/hooks/post-checkout`
-# Checks if the `rust-toolchain.toml` file has changed (indicating that the Rust version has
-# been updated), and if so runs the `scripts/setup-rust` script to install the default
-# toolchains and components.
+# To install the hook copy this file to `.git/hooks/post-checkout` or run
+# scripts/setup-rust install_hook
 
-set -eu
+set -u
 
-function main() {
-    # Set to "android", "desktop", or "ios" or leave empty.
-    # If empty this hook will not call the `setup-rust` script and only install the EXTRA_TARGETS
-    # and EXTRA_COMPONENTS.
-    local platform="${MULLVAD_SETUP_PLATFORM:-}"
-    # Any extra targets outside of the ones defined in `setup-rust` that should be installed.
-    local extra_targets="${MULLVAD_SETUP_EXTRA_TARGETS:-}"
-    # Any extra components outside of the ones defined in `setup-rust` that should be installed.
-    local extra_components="${MULLVAD_SETUP_EXTRA_COMPONENTS:-}"
+# Set to "android", "desktop", or "ios".
+MULLVAD_SETUP_PLATFORM="${MULLVAD_SETUP_PLATFORM:-}"
 
-    local setup_rust_script="scripts/setup-rust"
-    if [ ! -f "$setup_rust_script" ]; then
-        exit 0
-    fi
+SETUP_RUST_SCRIPT="scripts/setup-rust"
 
-    # Only query Rustup if the rust-toolchain.toml file has changed as a result of the checkout.
-    # shellcheck disable=SC2155
-    local changed=$(git diff "$1" "$2" --stat -- rust-toolchain.toml | wc -l)
+if [[ ! -f "$SETUP_RUST_SCRIPT" ]]; then
+    exit 0
+fi
 
-    if [ "$changed" -gt 0 ];
-    then
-        # Check installed targets vs required targets
-        # - 1 because we don't want to count the default target that is always installed by rustup
-        local installed_targets_count=$(( $(rustup target list --installed | wc -l) - 1))
+if [[ -z ${MULLVAD_SETUP_PLATFORM+x} ]]; then
+    echo "MULLVAD_SETUP_PLATFORM is not set, must be set to " >&2
+    echo "\`android\`, \`desktop\` or \`ios\`" >&2
+    exit 1
+fi
 
-        # - 6 because we don't want to count the default components that are installed by rustup
-        # (rustc, rust-std, cargo, rust-docs, rustfmt, clippy)
-        local installed_components_count=$(( $(rustup component list --installed | wc -l) - 6))
+git diff-tree --exit-code "$1".."$2" --quiet -- rust-toolchain.toml
 
-        # shellcheck disable=SC2155
-        local extra_targets_count=$(echo "$extra_targets" | wc -w)
-        # shellcheck disable=SC2155
-        local extra_components_count=$(echo "$extra_components" | wc -w)
-
-        if [ -n "$platform" ]; then
-            required_targets_count=$(( $("$setup_rust_script" "$platform" --print-targets | wc -w) + "$extra_targets_count" ))
-        else
-            required_targets_count="$extra_targets_count"
-        fi
-
-        if [ "$installed_targets_count" -lt "$required_targets_count" ]; then
-            if [ -n "$platform" ]; then
-                $setup_rust_script "$platform"
-            fi
-
-            if [ -n "$extra_targets" ]; then
-                echo "Installing extra targets"
-                # shellcheck disable=SC2086
-                rustup target add $extra_targets
-            fi
-        fi
-
-        if [ "$installed_components_count" -lt "$extra_components_count" ]; then
-            echo "Installing extra components"
-            # shellcheck disable=SC2086
-            rustup component add $extra_components
-        fi
-    fi
-}
-
-# Run script
-main "$@"
-
+# Exit code 1 means there was a change, 0 means no change.
+if [[ $? -eq 1 ]]; then
+    $SETUP_RUST_SCRIPT "$MULLVAD_SETUP_PLATFORM"
+fi
